name: CI Pipeline

on:
  push:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      run: docker build -t flask-devops-test .

    - name: Run container and test
      run: |
        docker run -d -p 5000:5000 --name app flask-devops-test
        sleep 5
        curl --fail http://localhost:5000 || exit 1

